.mso gproto.tmac
.nr include_flag 1
.so fork.tmac
.so argeater.3.d/prototypes.3
.\" For slightly-indented code, augment EX/EE with TEX/TEE
.TH argeater 3 2024-1-03
.SH NAME
.B argeater
\- library for parsing and documenting command line arguments
.SH LIBRARY
.PP
link with
.I -largeater
.\"
.so argeater.3.d/synopsis.3

.SH DESCRIPTION
.so argeater.3.d/desc_intro.3
.\" Structures documentation
.so argeater.3.d/ae_item.3
.so argeater.3.d/arg_clone.3
.\" Functions documentation
.so argeater.3.d/clone_args.3
.so argeater.3.d/argeater_process.3
.\"
.so argeater.3.d/ae_action_setter.3
.\"
.so argeater.3.d/example.3
