.so fork.tmac
.SH EXAMPLE
.PP
The following example uses nearly every resource in the
library.  It omits only
.B argeater_dump_args
which is used for debugging.
.PP
.PP
Compile the following source code with:
.in 12
.EX
cc -o example test_example.c libargeater.a
.EE
.in
.sp
.EX
// file: test_example.c

\(shinclude <argeater.h>
\(shinclude <alloca.h>
\(shinclude <stddef.h>
\(shinclude <stdio.h>
\(shinclude <stdbool.h>

\fB// declare variables for the action map:\fP
const char *help_flag = NULL;
const char *filename = NULL;
const char *verbose_flag = NULL;
const char *favcolor = NULL;
bool silent = 0;


\fB// attach variables to actions:\fP
AE_ITEM actions[] = {
  { &help_flag,    \(dqhelp\(dq,     \(aqh\(aq,  AET_FLAG_OPTION },
  { &filename,     \(dqfilename\(dq, \(aq\(rs0\(aq, AET_ARGUMENT },
  { &verbose_flag, \(dqverbose\(dq,  \(aqv\(aq,  AET_FLAG_OPTION },
  { &favcolor,     \(dqfavcolor\(dq, \(aqc\(aq,  AET_VALUE_OPTION },
  { (const char**)&silent, \(dqsilent\(dq, \(aqs\(aq, AET_FLAG_OPTION,
    NULL, NULL, argeater_bool_setter }
};

\fB// Use macro to intializa a AE_MAP instance:\fP
AE_MAP action_map = INIT_MAP(actions);

\fB// Use library functions to build a usage display:\fP
void show_help(AE_MAP *map, const char *cmdname)
{
   argeater_show_usage(map, cmdname);
   argeater_show_options(map, 3);
   argeater_show_arguments(map, 3);
}

int main(int argc, const char **argv)
{
   if (argc < 2)
   {
      show_help(&action_map, *argv);
      return 1;
   }

   \fB// Collect arguments into a linked list:\fP
   ACLONE *clones = CLONE_ARGS(argc, argv);

   \fB// \(dqeat\(dq the arguments to set variables:\fP
   if (argeater_process(clones, &action_map))
   {
      \fB// Read mapped variables and respond according to plan\fP
      if (help_flag)
      {
         \fB// (First CL argument is command name:)\fP
         show_help(&action_map, *argv);
         return 1;
      }
      else
        argeater_dump_actions(&action_map);
   }
   else
      fprintf(stderr, \(dqError processing arguments.\(rsn\(dq);

   return 0;
}
.EE
.SS ACTION_SETTER EXAMPLE
.PP
This example illustrates how a custom data type might be handled.
.TS
tab(|);
l lx.
1|T{
Declare a
.B status variable
in which the value will be stored.
T}
2|T{
A
.B handler function
must match the signature of the
.B action_setter
function pointer.
Cast the
.I target
argument to the appropriate data type and set it according to
.IR value .
T}
3|T{
Make an
.B AE_ITEM element
that refers to the handle function.
Make sure the
.I help_desc
member of
.B AE_ITEM
explains how the data is used.
T}
.TE
.PP
.EX
// For strtol function in set_debug_level:
\(shinclude <stdlib.h>

// Declare the \fBstatus variable\fP
int debug_level = 0;

// Implement the \fBhandler function\fP.
bool set_debug_level(const char **target, const char *arg)
{
   char *end;
   int level = (int)strtol(arg, &end, 10);
   if (end == arg)
      fprintf(stderr, \(dq\(aq%s\(aq is not a number.\(rsn\(dq, arg);
   else if (level<0 || level>3)
      fprintf(stderr, \(dq\(aq%d\(aq is not a valid debug level.\(rsn\(dq, level);
   else
   {
      *(int*)target = level;
      return true;
   }

   return false;
}

// Create an \fBAE_ITEM element\fP referencing the \fBhandler function\fP.
AE_ITEM actions[] = {
  { (const char**)&debug_level,
   \(dqdeblev\(dq,
   \(aqd\(aq,
   AET_VALUE_OPTION,
   \(dqThe debug level can be 0, 1, 2, or 3\(dq,
   \(dqdebug level\(dq,
   set_debug_level }
};

.EE
