.TH README 1
.SH Disclaimer
I am going to try using groff source for the README file, as it's
more convenient to access in the console than a markdown file.xs
.SH OVERVIEW
.PP
This subdirectory full of man page fragments is a development
convenience: each logical topic can have its own file through which
development can take place.  Each fragment can be viewed individually
either in
.B emacs
or using
.IP
.EX
man -l synopsis.3
.EE
.SS fork.tmac
.PP
This is an includable file that, in one line, can ensure that other
includes are handled and that there is a
.B .TH
statement to activate man-page processing.
.PP
There is an empty (save for a comment) shadow
.B fork.tmac
in the project root directory that will enable
.B soelim
to successfully compile all the source pages.
.PP
.B NOTE:
this macro file is using the extension
.B tmac
so the contents of the source file will not be included in the
compiled version to be installed at
.BR "/usr/share/man/man3" .
