.so fork.tmac
.SH SYNOPSIS
.B \(shinclude <argeater.h>

.p_argeater_process
.br
.p_argeater_clone_args
.br
.p_argeater_clone_word_list

.PP
.p_argeater_show_usage
.br
.p_argeater_show_options
.br
.p_argeater_show_arguments

.PP
.p_argeater_dump_actions
.PP
.p_action_setter
.PP
.p_argeater_string_setter
.p_argeater_int_setter
.PP
.B \(sh -------- Structs --------
.PP
.p_AI_ITEM
.PP
.p_AE_TYPE
.PP
.p_AE_MAP
.PP
.p_ACLONE
.PP
.B \(sh ------- AE_ITEM Type Macros -------
.sp 0
.B AET_ARGUMENT
.sp 0
.B AET_FLAG_OPTION
.sp 0
.B AET_VALUE_OPTION
.sp 1
.B \(sh ------- Initialization Macros -------
.sp 0
.B INIT_MAP \c
.RI ( AE_ITEM_ARRAY )
.sp 0
.B CLONE_ARGS \c
.RI ( ACLONE_ARRAY ", " ARGC ", " ARGV )
