.so fork.tmac
.SH SYNOPSIS
.B \(shinclude <argeater.h>

.p_argeater_process
.p_argeater_clone_args

.p_argeater_show_usage
.p_argeater_show_options
.p_argeater_show_arguments

.p_argeater_dump_actions

.PP
.B \(sh -------- Structs --------

.p_AI_ITEM

.p_AE_TYPE

.p_AE_MAP

.p_ACLONE

.PP
.B \(sh ------- AE_ITEM Type Macros -------
.sp 0
.B AET_ARGUMENT
.sp 0
.B AET_FLAG_OPTION
.sp 0
.B AET_VALUE_OPTION
.sp 1
.B \(sh ------- Initialization Macros -------
.sp 0
.B INIT_MAP(AE_ITEM_ARRAY)
.sp 0
.BR CLONE_ARGS \c
.RI ( ACLONE_ARRAY ", " ARGC ", " ARGV )
